name: autosplash
description: Wallpapers App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  cupertino_icons: ^0.1.3
  firebase_storage: null
  flushbar: ^1.10.4
  # flutter_cache_manager: ^1.1.3
  font_awesome_flutter: ^8.8.1
  form_field_validator: ^1.0.1
  google_fonts: ^1.1.0
  http: ^0.12.0+4
  image_downloader: ^0.20.1
  material_design_icons_flutter: ^4.0.5755
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.3
  progress_dialog: ^1.2.4
  random_string: ^2.0.1
  textfield_tags: ^1.1.0+1
  url_launcher: ^5.4.2
  url_launcher_web: ^0.1.1+1
  wallpaper_manager: ^1.0.10
  
  # flutter_cache_manager: ^2.0.0
  # cached_network_image: ^2.2.0+1
  cached_network_image: ^2.4.1
  characters: ^1.0.0
  # cloud_firestore: ^0.12.9+4
  cloud_firestore: ^0.12.11
  # firebase_auth: ^0.16.1
  firebase_auth: ^0.16.1
  # firebase_core: ^0.4.2+1
  firebase_core: ^0.4.5
  flutter_image_compress: ^0.7.0
  flutter_launcher_icons: null
  flutter_spinkit: "^4.0.0"
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  provider: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
#  adaptive_icon_background: "assets/launcher/background.png"
#  adaptive_icon_foreground: "assets/launcher/foreground.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
